### ISSUE TITLE
pubDate format is invalid

### ISSUE THREAD

**Issue by BasThomas** [Contravariance/website#9]
This isn't recognized by iTunes.

Here are some valid/invalid formats:

```
VALID   Thu, 18 Oct 2018 15:10:44 +0000
VALID   Tue, 16 Oct 2018 23:05:54 EDT
INVALID Thu, 18 Oct 2018 20:00:00 CEST
```

`+0000` is GMT; maybe we can try using `+0100` instead of CEST?

**Comment by terhechte** [comment]
Yeah, we can just try it, and re-generate, right?
